"""Behaviours added in V0.2 after the first benchmark run (each fixes a measured failure)."""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest

from treeengine import TreeEngine
from treeengine.core.text import lexical_score, stem
from treeengine.storage import SCHEMA_VERSION, SQLiteRepository
from treeengine.structure.pdf import running_lines


def test_parent_section_own_text_can_be_the_answer(engine: TreeEngine) -> None:
    doc = engine.ingest_text(
        "# Guide\n\n## Troubleshooting\n\nCrashLoopBackOff is caused by application errors "
        "or missing configuration files.\n\n### Restart delay\n\nThe delay grows to five "
        "minutes.\n\n### Restart policy\n\nAlways is the default.\n",
        title="Guide",
    )
    res = engine.tree_search("What causes CrashLoopBackOff?", doc.id)
    assert [t.title for t in res.targets] == ["Troubleshooting"]
    assert res.own_text_target_ids == [res.targets[0].id]  # its own text, not the subtree
    assert "application errors" in res.evidence[0].content
    assert all(e.metadata["node_title"] == "Troubleshooting" for e in res.evidence)


def test_signal_uses_best_hit_not_volume(engine: TreeEngine) -> None:
    noisy = "\n\n".join(f"Widget note {i}: the widget is blue." for i in range(12))
    doc = engine.ingest_text(
        f"# Manual\n\n## Widgets everywhere\n\n{noisy}\n\n## Limits\n\n"
        "The widget storage limit is 1 MiB per widget.\n",
        title="Manual",
    )
    res = engine.tree_search("widget storage limit", doc.id)
    assert res.targets[0].title == "Limits"


def test_first_block_of_target_is_kept_without_word_overlap(engine: TreeEngine) -> None:
    doc = engine.ingest_text(
        "# App\n\n## Interactive API docs\n\nNow go to http://127.0.0.1:8000/docs.\n\n"
        "You will see the automatic interactive API documentation.\n\n"
        "The interactive documentation is generated by Swagger UI.\n\n"
        "The interactive API page is interactive.\n\n## Other\n\nUnrelated text.\n",
        title="App",
    )
    ev = engine.tree_search("Where is the interactive API documentation served?", doc.id).evidence
    assert any("8000/docs" in e.content for e in ev)  # kept even with zero word overlap


def test_stemming_and_word_boundaries() -> None:
    assert stem("shuffle") == stem("shuffling") == "shuffl"
    assert stem("partitions") == "partition"
    assert stem("供应链") == "供应链"
    assert lexical_score(["shuffle"], "By default no shuffling occurs") == 1.0
    assert lexical_score(["groupkfold"], "StratifiedGroupKFold") == 0.0
    assert lexical_score(["groupkfold"], "GroupKFold is a variation") == 1.0
    assert lexical_score(["供应"], "芯片供应不足") == 1.0


def test_fts_porter_stemming(engine: TreeEngine) -> None:
    doc = engine.ingest_text("# T\n\n## S\n\nBy default no shuffling occurs.\n", title="T")
    assert engine.search_text("shuffle", document_id=doc.id)


def test_migration_v1_to_v2_rebuilds_fts(tmp_path: Path) -> None:
    db = tmp_path / "v1.db"
    # a V0.1 database: FTS without porter, user_version = 1
    conn = sqlite3.connect(db)
    schema = (Path(__file__).parent.parent / "treeengine/storage/schema.sql").read_text("utf-8")
    schema = schema.replace(",\n    tokenize = 'porter unicode61'", "")
    conn.executescript(schema)
    conn.execute(
        "INSERT INTO documents VALUES ('d','markdown',NULL,'Doc',NULL,'x',NULL,'t','t','{}')"
    )
    conn.execute(
        "INSERT INTO nodes VALUES ('n','d',NULL,0,0,'Notes',NULL,NULL,'section',"
        "NULL,NULL,NULL,NULL)"
    )
    conn.execute(
        "INSERT INTO blocks VALUES ('b','d','n',0,'paragraph','no shuffling here',"
        "NULL,NULL,NULL,'{}')"
    )
    conn.execute(
        "INSERT INTO blocks_fts(rowid, block_id, document_id, title, content) "
        "SELECT rowid, id, document_id, 'Notes', content FROM blocks"
    )
    conn.execute("PRAGMA user_version = 1")
    conn.commit()
    conn.close()

    repo = SQLiteRepository(db)
    assert repo.schema_version == SCHEMA_VERSION == 2
    assert [b.id for b, _ in repo.fts_query(["shuffle"])] == ["b"]  # stemmed after rebuild
    assert repo.fts_integrity() == (1, 1)
    repo.close()


def test_pdf_running_headers_are_removed() -> None:
    pages, lines, pos = [], [], 0
    for p in range(1, 7):
        start = pos
        body = [f"Body text of page {p}, line {i}." for i in range(4)]
        for ln in ["Java 开发手册（黄山版）", *body, f"{p}/51"]:
            lines.append((pos, ln))
            pos += len(ln) + 1
        pages.append((p, start, pos - 1))
    noise = running_lines(lines, pages)
    kept = [lines[i][1] for i in range(len(lines)) if i not in noise]
    assert kept == [f"Body text of page {p}, line {i}." for p in range(1, 7) for i in range(4)]


def test_real_pdf_has_no_running_header_blocks(engine: TreeEngine, fixtures: Path) -> None:
    pytest.importorskip("pypdf")
    doc = engine.ingest(fixtures / "manual_bookmarks.pdf")
    assert engine.get_tree(doc.id)["roots"]  # synthetic PDF: nothing to strip, still intact


def test_table_of_contents_is_not_a_navigation_target(engine: TreeEngine) -> None:
    doc = engine.ingest_text(
        "# Book\n\n## 目录\n\n第一章 缓存设计\n第二章 线程池\n\n"
        "## 第一章 缓存设计\n\n缓存要设置过期时间。\n\n"
        "## 第二章 线程池\n\n线程池不允许使用 Executors 创建。\n",
        title="Book",
    )
    toc = next(n for n in engine.repo.get_document_nodes(doc.id) if n.title == "目录")
    assert toc.node_type == "toc"
    res = engine.tree_search("线程池怎么创建", doc.id)
    assert "目录" not in [t.title for t in res.targets]
    assert res.targets[0].title == "第二章 线程池"
